daytonaio/docs

src/content/docs/index.mdx

As discussed in #1, this will return in a future PR.

Remove dead link to Targets documentation on homepage

---

CODE_OF_CONDUCT.md
LICENSE
README.md
SECURITY.md
package.json

In addition to README, add LICENSE + corresponding field in `package.json`, the CODE_OF_CONDUCT, and the SECURITY information.
Closes #3 and #12.

Add README and common Daytona docs

---

src/content/docs/usage/workspaces.mdx

Adds procedures for forwarding ports from a Dev Environment to a local machine, and generating a shareable URL.
Fixes #11.

Add port forwarding procedures to Dev Environments page

---

src/content/docs/index.mdx

After some previous PRs, some of the links on the Docs home page stopped functioning. This PR fixes them.

Fix broken links on home page

---

package.json

When using Astro's in-built dev/preview servers through `package.json` scripts, they should listen on all interfaces by default.
This commit also makes the `start` script an alias of `dev` to cut down on duplication.
Fixes #52.

Add --host to Astro server commands in package.json scripts

---

src/components/Footer.astro

While this is still static, it'll change once we start publishing the OSS changelog to https://daytona.io/changelog.
In the meantime, this is a quick fix so the link isn't broken.

Fix broken changelog link in the Footer

---

src/content/docs/configuration/providers.mdx

Added a caution notice for `Remote User` in the Docker target section. Related to https://github.com/daytonaio/daytona/pull/708

feat: add non-root remote user caution

---

src/content/docs/index.mdx

Minor broken link on the docs homepage, go to /docs and check [the link to server docs](https://www.daytona.io/docs/#:~:text=to%20increase%20productivity.-,Daytona%20Server,-Learn%20about%20the).

docs: update server docs link

---

src/content/docs/about/what-is-daytona.mdx

- fixed minor text whitespace formatting issue in the [what is daytona](https://www.daytona.io/docs/about/what-is-daytona/) section
Current behavior:
Expected behavior:

fix: minor text whitespace formatting

---

src/content/docs/misc/telemetry.mdx

- added textual and visual additions and improvements per each sub-section
I have noticed the `daytona telemetry disable` command returns `unknown command "telemetry" for "daytona"`. 
Will this be supported in the future so I can leave the command as is (and additionally add support for enabling the telemetry with `daytona telemetry enable`), or should I remove it?

docs: telemetry section textual and visual improvements

---

src/components/Footer.astro

- modified "Need help? - Reach support" anchor tag hyperlink to link to daytona's slack community
This can be modified to link to any other support communication channel of preference (GitHub repository, issues, email, etc.)

docs: modify support anchor tag hyperlink

---

src/content/docs/configuration/providers.mdx
src/content/docs/installation/installation.mdx
src/content/docs/reference/cli.mdx
src/content/docs/usage/workspaces.mdx

- This pull request addresses issues with relative links in the documentation. Specifically, it removes the usage of `..` in all paths, replacing them with absolute paths to ensure that links work correctly in both development and production environments.
Fixes #92 
Before : ![Screenshot (112)](https://github.com/user-attachments/assets/6c41cd7f-2450-4ec8-9abf-787c637885ee)
After:

fix: Some links are broken at daytona.io documentation page

---

src/components/Footer.astro

- added version reference from package.json to footer
- fixes https://github.com/daytonaio/docs/issues/2
This eliminates the need to bump the release version in the footer for each new release. 
I will also try to do the same for the .mdx files so only package.json would need to be version bumped with each new release.

docs: footer version reference package.json

---

CONTRIBUTING.md
README.md

Updated the slack link from a static one to a Daytona redirect shortlink so we don't have to change the link once it expires.

chore: update slack link to daytona redirect

---

src/content/docs/installation/method/uninstall-macos.mdx
src/content/docs/installation/method/uninstall-unix.mdx

This PR resolves issue #90 by updating the uninstall instructions for both macOS and Unix systems.
- **Files changed**: `uninstall-macos.mdx`, `uninstall-unix.mdx`
- **Changes**:
- Updated the uninstall command in `uninstall-macos.mdx` to `sudo rm $(whereis daytona | awk '{print $2}')`.
- Made similar corrections in `uninstall-unix.mdx` to ensure accurate and consistent uninstall procedures.
This update ensures that users have the correct instructions for uninstalling `daytona` on both linux and macOS.

Fix: Uninstall Command in Daytona Documentation

---

astro.config.mjs
src/content/docs/about/getting-started.mdx
src/content/docs/configuration/providers.mdx
src/content/docs/configuration/targets.mdx
src/content/docs/usage/workspaces.mdx

Fixes https://github.com/daytonaio/docs/issues/122
Fixes https://github.com/daytonaio/docs/issues/127
Since there are now multiple providers available, the page can be restructured to:
`/configuration/providers#docker`
`/configuration/providers#aws`
`/configuration/providers#digitalocean`
`/configuration/providers#flyio`
Currently, these are available under `/configuration/providers#officially-supported-providers`.

docs: add new providers

---

tools/update-cli-reference.js

The current tool for updating the CLI reference has a hyperlink leading to an non-existing page. This pull request updates the hyperlink to lead to the correct page.

docs: fix cli reference hyperlink

---

.markdownlint-cli2.jsonc
src/content/docs/about/getting-started.mdx
src/content/docs/configuration/git-providers.mdx
src/content/docs/configuration/providers.mdx
src/content/docs/configuration/targets.mdx
src/content/docs/installation/installation.mdx
src/content/docs/installation/method/homebrew.mdx
src/content/docs/installation/method/nix.mdx
src/content/docs/installation/method/script-powershell.mdx
src/content/docs/installation/method/script-unix.mdx
src/content/docs/installation/method/uninstall-macos.mdx
src/content/docs/installation/method/uninstall-unix.mdx
src/content/docs/usage/builders.mdx
src/content/docs/usage/ide.mdx
src/content/docs/usage/prebuilds.mdx
src/content/docs/usage/projects.mdx
src/content/docs/usage/server.mdx
src/content/docs/usage/workspaces.mdx
src/styles/components/markdown.scss

> **@ivan-burazin**
> Takoder mislim da je problem ovaj indenting
> Mozda da stavimo sve da je alignano left
> nema veze jel menu, paragraf bullet ili sub bullet sve da je alignano lijevo
Applied consistent style indentation formatting to all sections. This can be ported to the enterprise documentation too once the open pull requests are merged so it can be applied to all sections at once.
Important changes: https://github.com/daytonaio/docs/commit/e14c44a5346e7094dfab377ff22880d8748a7f38 - this commit disables the MD029 indentation rule.
Example:
Before
After

docs: consistent style indentation formatting

---

astro.config.mjs
src/content/docs/about/getting-started.mdx
src/content/docs/configuration/providers.mdx
src/content/docs/configuration/targets.mdx
src/content/docs/installation/installation.mdx
src/content/docs/usage/builders.mdx
src/content/docs/usage/ide.mdx
src/content/docs/usage/prebuilds.mdx
src/content/docs/usage/projects.mdx
src/content/docs/usage/server.mdx
src/content/docs/usage/workspaces.mdx

This should fix the broken links & hyperlinks in the deployed and local documentation.

docs: fix broken links & hyperlinks

---

src/components/ThemeSelect.astro
src/styles/_color.scss

Change css style `body.light` to `html[data-theme="light"] body`.
Because the script appending className to the body classList is executed after the page is loaded, it causes flickering every time when enter a new page.

fix: light theme flickering

---

.devcontainer/devcontainer.json

This PR removes the hardcoded directory from devcontainer.json file which was causing the OnCreateCommand to fail when trying to run docs from Daytona OSS.

fix: remove hardcoded directory in devcontainer.json file

---

src/content/docs/usage/builders.mdx

Removed the Post Start Commands description from the Custom Image Builder. The start commands were removed from Daytona.

fix: remove post start commands description

---

src/content/docs/usage/workspaces.mdx

In regards to https://github.com/daytonaio/daytona/pull/1205, replaced the `--code` tip with `--no-ide`

fix: replace --code tip with --no-ide

---

src/styles/_color.scss
src/styles/components/markdown.scss

To match the Dotfiles Insider blog.

docs(style): green code/blockquote text value

---

src/content/docs/sdk/index.mdx

The previous solution works on localhost, but doesn't seem to properly recognize the sdk paths when deployed. This pull request should fix the paths issue as it redirects from the root (daytona.io) to the `/docs/sdk/` paths.
@Tpuljak @ivan-burazin

docs: fix sdk index

---

astro.config.mjs
src/components/TableOfContentsList.astro

Closes #263 
ToC sidebar before:
ToC sidebar after:

refactor: set max heading level to 4 for toc sidebar

---

src/components/Sidebar.astro

Temporarily hiding CLI ref from the main menu until the installation and usage steps are specified

fix: temporarily hide CLI ref from menu
