README.md

Change `npm` refs to `yarn` in README

---

src/content/docs/installation/installation.mdx

Add installation instructions for Homebrew

---

src/content/docs/usage/workspaces.mdx

Add note about VS Code - Browser to Workspaces page

---

astro.config.mjs
src/content/docs/configuration/providers.mdx

Covers the basic architecture of Providers, their relationship to Targets, and some useful procedures.
Closes #7.

configuration/providers: new documentation

---

src/components/Footer.astro

`Daytona Platform Inc.` => `Daytona Platforms, Inc.`

Fix company name in footer

---

src/content/docs/installation/installation.mdx

Use new Aside component in the Installation guide

---

src/components/Version.astro

Strip patch from Version component

---

src/styles/_color.scss
src/styles/components/markdown.scss

Fixing text colors to be visible on light mode

Fix colours on light mode

---

src/content/docs/usage/builders.mdx

Since it doesn't add much, remove the "Supported Builders" h2 heading and bump each builder to h2 level.

Move individual Builders to h2 level

---

src/content/docs/configuration/providers.mdx
src/content/docs/usage/workspaces.mdx

Change numbers >10 to words across the docs

---

src/content/docs/usage/builders.mdx

https://github.com/daytonaio/daytona/pull/660

Add instructions to set custom build registry

---

src/content/docs/installation/installation.mdx
src/content/docs/installation/method/homebrew.mdx
src/content/docs/installation/method/nix.mdx
src/content/docs/installation/method/script-powershell.mdx
src/content/docs/installation/method/script-unix.mdx
src/content/docs/installation/method/uninstall-unix.mdx

* Installation procedures split into partials
* Installation guide split into sections based on OS (Linux, macOS, Windows)
* Added uninstall/upgrade instructions for Homebrew
* Added uninstall instructions for official method
Fixes #54, fixes #46, fixes #45.

Restructure installation, add new procedures and update references

---

src/content/docs/configuration/git-providers.mdx

Add Gitness information to Git Providers docs

---

astro.config.mjs
package.json
src/content/docs/reference/api.mdx
tools/update-server-reference.js

For users who want to have easily accessible knowledge of Daytona's REST API, this reference will be provided in addition to.
This is a __draft PR__ subject to change; please hold review comments until it's left draft status. We can likely ditch the custom script and use [HiDeoo/starlight-openapi](https://github.com/HiDeoo/starlight-openapi), but in any case, we want this reference to look prettier than it currently is here.

Add API reference for the server

---

src/content/docs/usage/workspaces.mdx

This PR addresses [Daytona PR #691](https://github.com/daytonaio/daytona/pull/691)

add workspace create flags usage tip

---

astro.config.mjs
src/content/docs/index.mdx
src/content/docs/usage/builders.mdx
src/content/docs/usage/ide.mdx
src/content/docs/usage/ides.mdx
src/content/docs/usage/workspaces.mdx

- added textual additions and improvements per each sub-section
- added visual outputs when executing the terminal commands with explanations
- all changes have been tested and previewed locally

docs: workspaces section textual and visual improvements

---

src/styles/components/markdown.scss

- removed text code block copy icon 
Fixes https://github.com/daytonaio/docs/issues/99

style: remove text code block copy icon

---

src/content/docs/configuration/providers.mdx

- added textual additions and improvements per each sub-section
- added visual outputs when executing the cli commands with explanations
- added list targets section with `daytona target list` command with its descriptions and cli commands
- organized the structure of content
- fixed inter-linking between sections (fyi: this is already covered by this issue: https://github.com/daytonaio/docs/issues/92, but was unsure whether it will get merged [if yes, i can delete this fix so there are no conflicts])
- all changes have been tested and previewed locally

docs: providers section textual and visual improvements

---

src/content/docs/configuration/git-providers.mdx

- added textual additions and improvements per each sub-section
- added visual outputs when executing the cli commands with explanations
- organized the structure of content
- all changes have been tested and previewed locally

docs: git providers section textual and visual improvements

---

src/content/docs/configuration/git-providers.mdx
src/content/docs/configuration/providers.mdx
src/content/docs/installation/method/homebrew.mdx
src/content/docs/installation/method/nix.mdx
src/content/docs/installation/method/script-powershell.mdx
src/content/docs/installation/method/script-unix.mdx
src/content/docs/installation/method/uninstall-macos.mdx
src/content/docs/installation/method/uninstall-unix.mdx
src/content/docs/usage/builders.mdx
src/content/docs/usage/ide.mdx
src/content/docs/usage/workspaces.mdx

- removed prerequisites and procedures notes that seemed repetitive and over-explaining based on this comment https://github.com/daytonaio/docs/pull/59#discussion_r1635001223
- fixes https://github.com/daytonaio/docs/issues/66

docs: remove prerequisites and procedures notes

---

src/content/docs/usage/ide.mdx

- added individual process for each IDE  (`/usage/ide#vs-code`, `/usage/ide#vs-code-browser`,...)

docs: add individual ide process

---

src/content/docs/usage/workspaces.mdx

Fixes https://github.com/daytonaio/docs/issues/118

docs: fix incorrect redirect

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json

Updated the devcontainer config to run as the `daytona` user now and fixed the git repo dubious ownership that occurred.

chore: update devcontainer to run as daytona user

---

src/content/docs/index.mdx

This pull request contains updates of the index (homepage) file to include the newly added sections.

docs: update index with new sections

---

src/content/docs/about/getting-started.mdx
src/content/docs/configuration/targets.mdx
src/content/docs/installation/installation.mdx

Fixes https://github.com/daytonaio/docs/issues/129

docs: add docker local & remote server requirements

---

src/content/docs/usage/workspaces.mdx

Fixes https://github.com/daytonaio/docs/issues/132

docs: add workspace samples entry

---

src/content/docs/installation/installation.mdx

Fixes https://github.com/daytonaio/docs/issues/130

docs: add wsl ssh client setup instructions note

---

src/content/docs/configuration/providers.mdx

fix error docker target config link

fix error docker target config link

---

src/content/docs/usage/workspaces.mdx

Fixes https://github.com/daytonaio/docs/issues/158

docs: add workspace multi-projects

---

src/content/docs/configuration/git-providers.mdx

Fixes https://github.com/daytonaio/docs/issues/168

docs: add git providers update

---

src/content/docs/usage/builders.mdx
src/content/docs/usage/projects.mdx

Fixes https://github.com/daytonaio/enterprise-docs/issues/161

docs: builders dev container & modify layout

---

src/content/docs/usage/workspaces.mdx

Fixes https://github.com/daytonaio/docs/issues/167

docs: update daytona create workspace section

---

src/content/docs/usage/workspaces.mdx

Fixes https://github.com/daytonaio/docs/issues/173

docs: remove forward --public flag section

---

src/content/docs/configuration/targets.mdx

feat: set default target note

---

src/content/docs/tools/cli.mdx
tools/update-cli-reference.js

Related to [#1274](https://github.com/daytonaio/daytona/pull/1274)

feat: add bash autocompletion instructions

---

src/content/docs/about/getting-started.mdx
src/content/docs/configuration/providers.mdx
src/content/docs/configuration/targets.mdx
src/content/docs/usage/workspaces.mdx

Fixes https://github.com/daytonaio/docs/issues/187

docs: add gcp provider & target

---

src/components/Header.astro
src/components/Search.jsx

Fixes https://github.com/daytonaio/docs/issues/195

docs: hide search without .env set

---

package.json

To automatically index the search results and update the output in the `search.json` file. This can then be used to connect the [JSON connector](https://www.algolia.com/doc/guides/sending-and-managing-data/send-and-update-your-data/connectors/json/) and automatically update the search results.
Example of running it locally:

feat: add update search to build script

---

src/content/docs/installation/installation.mdx
src/content/docs/installation/method/homebrew.mdx
src/content/docs/installation/method/uninstall.mdx

Fixes https://github.com/daytonaio/docs/issues/208

docs: modify installation section side menu

---

src/content/docs/misc/troubleshooting.mdx

Fixes https://github.com/daytonaio/docs/issues/130

docs: add wsl2 ssh client troubleshooting setup

---

src/content/docs/configuration/providers.mdx

Fixes https://github.com/daytonaio/docs/issues/202

docs: add azure provider service principal note

---

astro.config.mjs
src/content/docs/configuration/container-registries.mdx

Fixes https://github.com/daytonaio/docs/issues/206

docs: add container registries

---

src/content/docs/about/getting-started.mdx
src/content/docs/usage/ide.mdx

Fixes https://github.com/daytonaio/docs/issues/230

docs: add vscode insiders, vscodium, & windsurf ide

---

.markdownlint-cli2.jsonc
src/content/docs/installation/installation.mdx
src/content/docs/sdk/configuration.mdx
src/content/docs/sdk/file-system-operations.mdx
src/content/docs/sdk/getting-started.mdx
src/content/docs/sdk/git-operations.mdx
src/content/docs/sdk/language-server-protocol.mdx
src/content/docs/sdk/process-code-execution.mdx
src/content/docs/sdk/workspace-management.mdx
src/styles/components/markdown.scss

Fixes https://github.com/daytonaio/docs/issues/223
Fixes https://github.com/daytonaio/docs/issues/225
Fixes https://github.com/daytonaio/docs/pull/226

docs: refactor sdk code snippets & content

---

src/content/docs/sdk/index.mdx

Fixes https://github.com/daytonaio/docs/issues/236

docs: fix sdk index redirect

---

src/content/docs/configuration/api-keys.mdx
src/content/docs/configuration/providers.mdx
src/content/docs/configuration/target-config.mdx
src/content/docs/usage/ide.mdx
src/content/docs/usage/workspaces.mdx

I will open separate pull requests for changing the rest of the hyperlinks as I am also updating the getting started section with the refactored changes.
@Tpuljak @ivan-burazin

docs: update hyperlinks and spacings

---

src/content/docs/index.mdx

Updated index items to match the refactored changes.
@Tpuljak @ivan-burazin

docs: update index items

---

src/content/docs/installation/installation.mdx
src/content/docs/installation/method/uninstall-windows.mdx

Fixes https://github.com/daytonaio/docs/issues/228

docs: add windows uninstallation guide

---

package.json
public/llms-full.txt
public/search.json
src/content/docs/index.mdx
yarn.lock

https://github.com/user-attachments/assets/42e22e7c-71d6-4fd8-a586-1d7d7adc1465

refactor: quick start; bump starlight version to ^0.22.0

---

public/llms-full.txt
public/search.json
src/content/docs/getting-started.mdx

Extra `.md` changes  got autogenerated from `yarn build`

feat: web terminal tip on getting started page

---

src/content/docs/getting-started.mdx

The "Connect to an LLM" example makes more sense now since it actually executes the code from Claude instead of just prompting it

fix: llm example

---

public/llms-full.txt
public/llms.txt
tools/update-llms.js

Declutters the llms-full.txt file by ~10% and adds a version+date header to both
Closes #254

fix: declutter llms files

---

public/llms-full.txt
public/llms.txt
public/search.json
src/content/config.ts
src/content/docs/api-keys.mdx
src/content/docs/organizations.mdx
src/content/docs/quotas.mdx

Accout Management in the menu:
API Keys subpage:
Settings snippet
Not much to write here since these are the only settings for now so I opted for a subheading on the Organizations subpage instead
Quotas subpage:
Closes #299 
Closes #300 
Closes #301 
Closes #302

feat: account management

---

src/content/config.ts
src/content/docs/images.mdx

feat: clarify docker oci compatible images

---

src/content/docs/getting-started.mdx
src/content/docs/index.mdx

Add llms.txt and llms-full.txt links to documentation to help users leverage AI assistants for development.

feat: add links to LLMs context files

---

public/llms-full.txt
public/llms.txt
public/search.json
src/content/config.ts
src/content/docs/file-system-operations.mdx
src/content/docs/getting-started.mdx
src/content/docs/preview-and-authentication.mdx
src/content/docs/process-code-execution.mdx
src/content/docs/python-sdk/charts.mdx
src/content/docs/python-sdk/code-run-params.mdx
src/content/docs/python-sdk/daytona.mdx
src/content/docs/python-sdk/errors.mdx
src/content/docs/python-sdk/execute-response.mdx
src/content/docs/python-sdk/file-system.mdx
src/content/docs/python-sdk/git.mdx
src/content/docs/python-sdk/lsp-server.mdx
src/content/docs/python-sdk/process.mdx
src/content/docs/python-sdk/sandbox.mdx
src/content/docs/sandbox-management.mdx
src/content/docs/typescript-sdk/charts.mdx
src/content/docs/typescript-sdk/daytona.mdx
src/content/docs/typescript-sdk/errors.mdx
src/content/docs/typescript-sdk/execute-response.mdx
src/content/docs/typescript-sdk/file-system.mdx
src/content/docs/typescript-sdk/git.mdx
src/content/docs/typescript-sdk/lsp-server.mdx
src/content/docs/typescript-sdk/process.mdx
src/content/docs/typescript-sdk/sandbox.mdx

Also separates uploading, downloading, deleting files
Some other cleanups/reformats

feat: preview and authentication, exec env, multi file upload
